import type { Metadata } from "next";
import { Cormorant_Garamond, Alex_Brush } from "next/font/google";
import { SITE_URL } from "@/lib/site";
import { resolveRobots } from "@/lib/seo";
import { getSiteChrome } from "@/lib/homepage";
import { hexToRgbTriplet } from "@/lib/color";
import "./globals.css";

export const dynamic = "force-dynamic";

const displayFont = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-display",
});

const scriptFont = Alex_Brush({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-script",
});

// Branded 1200x630 PNG generated by app/opengraph-image.tsx
const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;

// Google Analytics (GA4) — optional. Set NEXT_PUBLIC_GA_ID in .env to enable;
// nothing is loaded when it is empty.
const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_ID || "";

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "San Gennaro Catacombs Tickets",
  url: SITE_URL,
  description:
    "Independent guide to San Gennaro Catacombs tickets and guided visits in Naples — compare bookable options and reserve your time slot.",
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "San Gennaro Catacombs Tickets",
  url: SITE_URL,
};

export function generateMetadata(): Metadata {
  const robots = resolveRobots(false);

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: "San Gennaro Catacombs Tickets | Guided Visits in Naples (2026)",
      template: "%s | San Gennaro Catacombs Tickets",
    },
    description:
      "Compare San Gennaro Catacombs tickets and guided visits in Naples. See what each option includes, then reserve your time slot with instant mobile confirmation.",
    keywords: [
      "San Gennaro Catacombs Tickets",
      "San Gennaro Catacombs Naples",
      "Catacombs of San Gennaro tickets",
      "San Gennaro Catacombs guided tour",
      "San Gennaro Catacombs opening hours",
      "Naples catacombs tickets",
      "Catacombe di San Gennaro biglietti",
      "San Gennaro Catacombs how to visit",
    ],
    alternates: {
      canonical: "/",
    },
    icons: {
      icon: [
        { url: "/favicon.svg", type: "image/svg+xml" },
        { url: "/icon", type: "image/png" },
      ],
      apple: "/apple-icon",
    },
    robots,
    openGraph: {
      title: "San Gennaro Catacombs Tickets | Guided Visits in Naples",
      description:
        "Compare San Gennaro Catacombs tickets and guided visits in Naples. Reserve your time slot with instant mobile confirmation.",
      type: "website",
      url: SITE_URL,
      siteName: "San Gennaro Catacombs Tickets",
      images: [{ url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: "San Gennaro Catacombs Tickets — Naples" }],
    },
    twitter: {
      card: "summary_large_image",
      title: "San Gennaro Catacombs Tickets | Guided Visits in Naples",
      description:
        "Compare San Gennaro Catacombs tickets and guided visits in Naples. Reserve your time slot with instant mobile confirmation.",
      images: [DEFAULT_OG_IMAGE],
    },
  };
}

function buildThemeStyle(theme: { primary: string; secondary: string; dark: string; accent: string }) {
  const vars: [string, string | null][] = [
    ["--color-maya-gold", hexToRgbTriplet(theme.primary)],
    ["--color-maya-emerald", hexToRgbTriplet(theme.secondary)],
    ["--color-maya-charcoal", hexToRgbTriplet(theme.dark)],
    ["--color-gold-400", hexToRgbTriplet(theme.accent)],
    ["--color-chichen-gold", hexToRgbTriplet(theme.primary)],
    ["--color-chichen-navy", hexToRgbTriplet(theme.secondary)],
    ["--color-chichen-charcoal", hexToRgbTriplet(theme.dark)],
  ];
  const declarations = vars
    .filter(([, value]) => value !== null)
    .map(([name, value]) => `${name}:${value};`)
    .join("");
  return declarations ? `:root{${declarations}}` : "";
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { theme } = await getSiteChrome();
  const themeStyle = buildThemeStyle(theme);

  return (
    <html lang="en" className={`${displayFont.variable} ${scriptFont.variable}`}>
      <head>
        {GA_MEASUREMENT_ID ? (
          <>
            <script async src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`} />
            <script
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${GA_MEASUREMENT_ID}');
                `,
              }}
            />
            <link rel="preconnect" href="https://www.googletagmanager.com" />
            <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
          </>
        ) : null}
      </head>
      <body className="font-body bg-stone-50 text-stone-900 antialiased">
        {themeStyle && <style dangerouslySetInnerHTML={{ __html: themeStyle }} />}
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </body>
    </html>
  );
}
